site_name: data-integration
site_description: Easily ingest historical or incremental raw data into C1W
site_author: QuantumBlack, AI by McKinsey
# site_url: Origin repository/ or documentation here. E.g. https://github.com/organization/repository

# Repository
repo_name: McK-Internal/customerone-w
repo_url: https://github.com/McK-Internal/customerone-w

# Copyright
copyright: "Copyright (c) 2016 - present
  QuantumBlack Visual Analytics Ltd (a McKinsey company).
  All rights reserved.

  This software framework contains the confidential and proprietary information
  of QuantumBlack, its affiliates, and its licensors. Your use of these
  materials is governed by the terms of the Agreement between your organisation
  and QuantumBlack, and any unauthorised use is forbidden. Except as otherwise
  stated in the Agreement, this software framework is for your internal use
  only and may only be shared outside your organisation with the prior written
  permission of QuantumBlack."

# Page tree
nav:
  - About: ./README.md

# Theme
theme:
  name: material
  language: en
#  favicon:
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs.link
    - content.code.annotate
  palette:
    scheme: quantum-black

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins
plugins:
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - .

# CSS
extra_css:
  - stylesheets/extra.css
